pdf("synth2.pdf", width=14, height=6)
synth1 <- paste0(rand.nseq(12000), rand.nseq(15000, f=c(0.5, 0.25, 0.125, 0.125)), kmer.rep("TGT", 550), rand.nseq(1500), rand.nseq(2000), sep="")
synthcmplx <- kmer.complexity(seq=synth1, k=2, window.size=1024, olap=TRUE)
plot.entropy(synthcmplx)
regions <- vector.regions(synthcmplx[[1]], 2, 1024)
regions_b <- vector.borders(regions, synthcmplx[[1]], 2)
plot.drawseq(as.character(synth1), regions_b, synthcmplx[[1]])

synth2 <- paste0(rand.nseq(12000, n), kmer.rep("CG", 800), rand.nseq(12300, n), kmer.rep("TGGT", 850), rand.nseq(1500), kmer.rep("AA", 100), rand.nseq(2000), kmer.rep("TGC", 254), rand.nseq(8500), sep="")
synth2 <- kmer.mutate(DNAString(synth2), 10000)
synthcmplx <- kmer.complexity(seq=as.character(synth2), k=2, window.size=1024, olap=TRUE)
plot.entropy(synthcmplx)
regions <- vector.regions(synthcmplx[[1]], 3, 1024)
regions_b <- vector.borders(regions, synthcmplx[[1]], 3)
plot.drawseq(as.character(synth2), regions_b[1,], synthcmplx[[1]])

synth4 <- paste0(rand.nseq(2400, n), kmer.rep("CG", 550), rand.nseq(1450, n))
synth4 <- kmer.mutate(DNAString(synth4), 200)
synthcmplx <- kmer.complexity(seq=as.character(synth4), k=2, window.size=1024, olap=TRUE)
plot.entropy(synthcmplx)
regions <- vector.regions(synthcmplx[[1]], 3.2, 1024)
regions_b <- vector.borders(regions, synthcmplx[[1]], 3.2)
plot.drawseq(as.character(synth1), regions_b[1,], synthcmplx[[1]])
dev.off()

pdf("realdata.pdf", width=14, height=6)
dna_data <- read.fasta(14)
data <- entropy.analyze(dna_data, window_s, k=4)
ent <- kmer.complexity(seq=dna_data$dna[1], k=2, window.size=512, olap=TRUE)
r <- (data[[1]]$regions[1,]$lborder-800):(data[[1]]$regions[1,]$stop+400)
plot(r, ent[[1]][r], type="l")
plot.drawseq(as.character(dna_data$dna[1]), data[[1]]$regions[1,], ent[[1]], offset=400)

r <- (data[[1]]$regions[2,]$lborder-800):(data[[1]]$regions[2,]$stop+400)
plot(r, ent[[1]][r], type="l")
plot.drawseq(as.character(dna_data$dna[1]), data[[1]]$regions[2,], ent[[1]], offset=400)

r <- (data[[1]]$regions[3,]$lborder-800):(data[[1]]$regions[3,]$stop+400)
plot(r, ent[[1]][r], type="l")
plot.drawseq(as.character(dna_data$dna[1]), data[[1]]$regions[3,], ent[[1]], offset=400)

r <- (data[[1]]$regions[4,]$lborder-800):(data[[1]]$regions[4,]$stop+400)
plot(r, ent[[1]][r], type="l")
plot.drawseq(as.character(dna_data$dna[1]), data[[1]]$regions[4,], ent[[1]], offset=400)
dev.off()
